[package]
name = "knot"
version = "0.1.0"
authors = ["Adrian Sampson <adrian@radbox.org>"]

[dependencies]
pulldown-cmark = "^0.1.2"
getopts = "^0.2.11"
toml = "^0.4.5"
rust-crypto = "*"
base32 = "^0.3.1"
mustache = "^0.9.0"
